server:
  port: 8093

spring:
  application:
    name: service-shooping
  config:
    import: configserver:http://localhost:8081
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t