server:
  port: 8092

spring:
  application:
    name: service-customer
  config:
    import: configserver:http://localhost:8081
  cloud:
    config:
      uri: http://localhost:8081
      # username: root
      # password: s3cr3t