server:
  port: 8091

spring:
  application:
    name: service-product
  config:
    import: configserver:http://localhost:8081
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t