server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/OrlandoRodriguez93/digitalshop.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t